name: "Portainer Stack Deploy Action"
description: "Deploy or Update a Portainer Stack from a GitHub Repository"
author: "Shane"
branding:
  icon: "layers"
  color: "blue"

inputs:
  url:
    description: "Portainer URL"
    required: true
  token:
    description: "Portainer Token"
    required: true
  endpoint:
    description: "Portainer Endpoint ID"
    required: false
  name:
    description: "Stack Name"
    required: true
  file:
    description: "Compose File"
    required: false
    default: "compose.yaml"
  prune:
    description: "Prune Services"
    required: false
    default: "true"
  pull:
    description: "Pull Images"
    required: false
    default: "true"

runs:
  using: "node20"
  main: "dist/index.js"
