name: "Portainer Stack Deploy Action"
description: "Deploy or Update a Portainer Stack from a GitHub Repository"
author: "Shane"
branding:
  icon: "layers"
  color: "blue"

inputs:
  token:
    description: "Portainer Token"
    required: true
  url:
    description: "Portainer URL"
    required: true
  name:
    description: "Stack Name"
    required: true
  file:
    description: "Compose File"
    required: false
    default: "compose.yaml"
  endpoint:
    description: "Portainer Endpoint ID"
    required: false
  ref:
    description: "Repository Ref"
    required: false
  repo:
    description: "Repository URL"
    required: false
  tlsskip:
    description: "Skip TLS Repo Verification"
    required: false
    default: "false"
  prune:
    description: "Prune Services"
    required: false
    default: "true"
  pull:
    description: "Pull Images"
    required: false
    default: "true"
  username:
    description: "Repository Username"
    required: false
    default: ""
  password:
    description: "Repository Password"
    required: false
    default: ""

runs:
  using: "node20"
  main: "dist/index.js"
