blank_issues_enabled: true
contact_links:
  - name: "❔ Start a Discussion"
    about: Ask a general question or start a discussion
    url: https://github.com/cssnr/portainer-stack-deploy-action/discussions

  - name: "💬 Join Discord"
    about: Chat with us about anything
    url: https://discord.gg/wXy6m2X8wY

  - name: "📑 View Documentation"
    about: View the documentation site
    url: https://portainer-deploy.cssnr.com/

  - name: "🌐 Visit Actions Site"
    about: Browse more Actions
    url: https://actions.cssnr.com/
